linters-settings:
  goimports:
    local-prefixes: gitlab.com/digeon-inc/japan-association-for-clinical-engineers/e-privado

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - prealloc
    - testpackage
    - tparallel
    - exportloopref
    - thelper
    - gocognit
    - goimports
    - gofmt

run:
    go: "1.21"
